export const TABNAVIGATOR = 'TabNavigator';
export const CHARACTERS = 'Characters';
export const EPISODES = 'Episodes';
export const LOCATIONS = 'Locations';
export const SETTINGS = 'Settings';
export const CHAARACTERDETAIL = 'Character Detail';
export const FILTERCHARACTERS = 'Filter Characters';
export const SEARCHCHARACTERS = 'Search Characters';
export const WELCOME = 'Welcome';
